services:
  api:
    build: .
    container_name: urbansoccer_api
    ports:
      - "8000:8000"
    volumes:
      - ./urbansoccer_server:/app/urbansoccer_server
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_DB: ${MONGO_DB}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
      COQUI_TTS_URL: ${COQUI_TTS_URL}
    depends_on:
      mongo:
        condition: service_healthy
      ollama:
        condition: service_started
      coqui-tts:
        condition: service_started
    command: uvicorn urbansoccer_server.main:app --host 0.0.0.0 --port 8000 --reload

  mongo:
    image: mongo:7
    container_name: urbansoccer_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.runCommand({ ping: 1 }).ok' | grep 1 >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    container_name: urbansoccer_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  coqui-tts:
    image: ghcr.io/coqui-ai/tts:latest
    container_name: urbansoccer_tts
    restart: unless-stopped
    ports:
      - "5002:5002"
    volumes:
      - coqui_tts_data:/root/.local/share/tts
    environment:
      - COQUI_TOS_AGREED=1
    entrypoint: [
      "tts-server", 
      "--model_path", "/root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/", 
      "--config_path", "/root/.local/share/tts/tts_models--multilingual--multi-dataset--xtts_v2/config.json"
    ]

volumes:
  mongo_data:
  ollama_data:
  coqui_tts_data: